api {
web_server:http://localhost:8080
api_server:http://localhost:8008
files_server:http://localhost:8081
credentials {
"access_key"="HL7Y7JOQJ7YU9UEJQZ59BUT108OFAW"
"secret_key"="aXtuzItrEI7BF81TlRc7MhS87rL2YUVhpdRqdrhJ0YJOXm3-6j0szQ2gqNkJe6pOkUU"
}
}
