[project]
name = "just-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.5.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
]

[dependency-groups]
dev = [
    "bandit>=1.9.1",
    "mypy>=1.18.2",
    "pre-commit>=4.4.0",
    "ruff>=0.14.6",
]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
# E, W - стандартные ошибки pycodestyle
# F - pyflakes
# I - isort (сортировка импортов)
# B - flake8-bugbear (поиск багов)
select = ["E", "W", "F", "I", "B"]
ignore = []

[tool.mypy]
python_version = "3.12"
strict = true
ignore_missing_imports = true
exclude = ["docs/"]

[tool.bandit]
exclude_dirs = ["tests", ".venv"]
